# 1 改变当前工作目录（os.chdir方法）

# 2 删掉numpy数组中的 行/列（np.delete方法）

In [4]:
# 先导包
import numpy as np

# 创建一个示例数组
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# 删除第 1 行（索引为 0）
new_array1 = np.delete(array, 0, axis=0)
print(f"删掉第一行后的数组内容为：\n{new_array1}\n")

# 再删除第 1 列（索引为 0）
new_array2 = np.delete(new_array1, 0, axis=1)
print(f"再删掉第一列后的数组内容为：\n{new_array2}")

删掉第一行后的数组内容为：
[[4 5 6]
 [7 8 9]]

再删掉第一列后的数组内容为：
[[5 6]
 [8 9]]


## 3 np.nan方法

# 4 round方法（np）