# 一 导包及常用API

# 1 导入Scikit-learn库

In [1]:
import sklearn

# 2 Bunch格式说明

# 3 导入小规模数据集，数据包含在datasets里

## 3.1 导入鸢尾花数据集

In [2]:
# 导入鸢尾花数据集
from sklearn.datasets import load_iris

# 数据集实例化
iris = load_iris()

# 输出鸢尾花数据集
print(f"鸢尾花数据集的内容为：\n{iris}")

鸢尾花数据集的内容为：
{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4,

## 3.2 导入红酒数据集

In [3]:
# 导入红酒数据集
from sklearn.datasets import load_wine

# 数据集实例化
wine = load_wine()

# 输出红酒数据集
print(f"红酒数据集的内容为：\n{wine}\n")

# 由于wine是一个Bunch类型的数据，所以可以使用类似字典键值对的访问方式
print(f"红酒数据集的特征名字内容为：\n{wine.feature_names}")

红酒数据集的内容为：
{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

# 4 导入大规模数据集，需要从网上下载

# 二 特征工程

# 1 数据集的划分

## API：sklearn.model_selection

## sklearn.model_selection.train_test_split方法

In [4]:
# 导入鸢尾花数据集
from sklearn.datasets import load_iris

# 导入数据集划分API
from sklearn.model_selection import train_test_split

# 数据集实例化
iris = load_iris()

# 对鸢尾花数据集进行划分
x_train, x_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.25, random_state=37)

# 检验划分结果，这里正确的结果应该是测试集比例占25%
print(f"原数据特征值数组的形状为：{iris.data.shape}")
print(f"训练集的形状为：{x_train.shape}")
print(f"测试集的形状为：{x_test.shape}")

原数据特征值数组的形状为：(150, 4)
训练集的形状为：(112, 4)
测试集的形状为：(38, 4)


# 2 特征提取

## API：sklearn.feature_extraction

## 2.1 字典特征提取: sklearn.feature_extraction.DictVectorizer类

In [5]:
# 导入类对象
from sklearn.feature_extraction import DictVectorizer

# 准备示例数据
data = [{"city": "北京", "温度": 29}, {"city": "上海", "温度": 36}, {"city": "广州", "温度": 32}]

# 创建 DictVectorizer 实例
vectorizer = DictVectorizer(sparse=False)

# 使用fit_transform方法，将转换列表内的字典数据为特征矩阵
X = vectorizer.fit_transform(data)

# 输出特征矩阵和特征名称
print(X)
print(vectorizer.get_feature_names_out())

[[ 0.  1.  0. 29.]
 [ 1.  0.  0. 36.]
 [ 0.  0.  1. 32.]]
['city=上海' 'city=北京' 'city=广州' '温度']


## 2.2 文本特征提取：sklearn.feature_extraction.text.CountVectorizer类（计数）

### 2.2.1 英文文本特征抽取

特别注意：单个字母 和 标点符号 不会被计数。
       在使用中文时候，需要进行空格分开，不然会识别一整句话作为一个元素进行。

In [6]:
# 导入类对象
from sklearn.feature_extraction.text import CountVectorizer

# 准备示例数据
data = ["life is too short, i like python", "i like python, and i like math, too!"]

# 创建 CountVectorizer 实例，同时停用 and 和 is
vectorizer = CountVectorizer(stop_words=["and", "is"])

# 使用fit_transform方法，将转换列表内的字符串数据为特征矩阵
X = vectorizer.fit_transform(data)

# 输出特征矩阵和特征名称
print(X)
print(vectorizer.get_feature_names_out())

  (0, 0)	1
  (0, 5)	1
  (0, 4)	1
  (0, 1)	1
  (0, 3)	1
  (1, 5)	1
  (1, 1)	2
  (1, 3)	1
  (1, 2)	1
['life' 'like' 'math' 'python' 'short' 'too']


## 补充： toarray方法

In [7]:
# 导入类对象
from sklearn.feature_extraction.text import CountVectorizer

# 准备示例数据
data = ["life is too short, i like python", "i like python, and i like math, too!"]

# 创建 CountVectorizer 实例
vectorizer = CountVectorizer()

# 使用fit_transform方法，将转换列表内的字符串数据为特征矩阵
X = vectorizer.fit_transform(data)

# 输出特征矩阵和特征名称
print(X.toarray())
print(vectorizer.get_feature_names_out())

[[0 1 1 1 0 1 1 1]
 [1 0 0 2 1 1 0 1]]
['and' 'is' 'life' 'like' 'math' 'python' 'short' 'too']


## 2.2.2 中文文本特征抽取

In [8]:
# 先导包
import jieba

# 导入类对象
from sklearn.feature_extraction.text import CountVectorizer

# 准备示例数据
text = "我爱北京天安门，天安门上太阳升"

# 创建 CountVectorizer 实例
vectorizer = CountVectorizer()

# 使用fit_transform方法，将转换列表内的字符串数据为特征矩阵，注意列表中的字符串先进性了断句处理
X = vectorizer.fit_transform(jieba.cut(text))

# 输出特征矩阵和特征名称
print(X.toarray())
print(vectorizer.get_feature_names_out())

Building prefix dict from the default dictionary ...
Dumping model to file cache C:\Users\Lenovo\AppData\Local\Temp\jieba.cache
Loading model cost 1.028 seconds.
Prefix dict has been built successfully.


[[0 0 0]
 [0 0 0]
 [1 0 0]
 [0 1 0]
 [0 0 0]
 [0 1 0]
 [0 0 0]
 [0 0 1]]
['北京' '天安门' '太阳升']


## 2.3 文本特征提取：sklearn.feature_extraction.text.TfidfVectorizer类（检索、分类）

In [9]:
# 导入类对象
from sklearn.feature_extraction.text import TfidfVectorizer

# 准备示例数据
data = ["life is too short, i like python", "i like python, and i like math, too!"]

# 创建 CountVectorizer 实例，同时停用 and 和 is
vectorizer = TfidfVectorizer(stop_words=["and", "is"])

# 使用fit_transform方法，将转换列表内的字符串数据为特征矩阵
X = vectorizer.fit_transform(data)

# 输出特征矩阵和特征名称
print(X)
print(vectorizer.get_feature_names_out())

  (0, 3)	0.3793034928087496
  (0, 1)	0.3793034928087496
  (0, 4)	0.5330978245262535
  (0, 5)	0.3793034928087496
  (0, 0)	0.5330978245262535
  (1, 2)	0.4976748316029239
  (1, 3)	0.3540997415957358
  (1, 1)	0.7081994831914716
  (1, 5)	0.3540997415957358
['life' 'like' 'math' 'python' 'short' 'too']


# 3 特征预处理

## 3.1 无量纲化（适用于不同数组间 数值差异过大）

### 3.1.1 数据归一化：MinMaxScaler类

归一化：通过对原始数据进行变换把数据映射到[0, 1]（默认）之间

In [10]:
# 先导包
import pandas as pd

# 导入数据预处理包
from sklearn.preprocessing import MinMaxScaler

# 实例化
mms = MinMaxScaler()

# 读取数据
f = pd.read_csv("练习数据.csv")

# 选择待处理数据
data = f.iloc[: , :3]

# 使用fit_transform方法将数据归一化
data_new = mms.fit_transform(data)

# 对比
print(f"原数据内容为：\n{data}\n\n处理后的数据内容为：\n{data_new}")

原数据内容为：
     milage     Liters  Consumtime
0     40920   8.326976    0.953952
1     14488   7.153469    1.673904
2     26052   1.441871    0.805124
3     75136  13.147394    0.428964
4     38344   1.669788    0.134296
..      ...        ...         ...
995   11145   3.410627    0.631838
996   68846   9.974715    0.669787
997   26575  10.650102    0.866627
998   48111   9.134528    0.728045
999   43757   7.882601    1.332446

[1000 rows x 3 columns]

处理后的数据内容为：
[[0.44832535 0.39805139 0.56233353]
 [0.15873259 0.34195467 0.98724416]
 [0.28542943 0.06892523 0.47449629]
 ...
 [0.29115949 0.50910294 0.51079493]
 [0.52711097 0.43665451 0.4290048 ]
 [0.47940793 0.3768091  0.78571804]]


### 3.1.2 数据标准化：StandardScaler类

标准差：standard deviation

标准化：将数据转换为均值(mean)为 0、标准差(std)为 1 的标准正态分布。

In [11]:
# 先导包
import pandas as pd

# 导入数据预处理包
from sklearn.preprocessing import StandardScaler

# 实例化
sds = StandardScaler()

# 读取数据
f = pd.read_csv("练习数据.csv")

# 选择待处理数据
data = f.iloc[: , :3]

# 使用fit_transform方法将数据归一化
data_new = sds.fit_transform(data)

# 对比
print(f"原数据内容为：\n{data}\n\n处理后的数据内容为：\n{data_new}")

# 检查标准化后数据的均值和标准差
import numpy as np
print(f"\n标准化后数据的均值为：{np.mean(data_new)}\n标准差为：{np.std(data_new)}")

原数据内容为：
     milage     Liters  Consumtime
0     40920   8.326976    0.953952
1     14488   7.153469    1.673904
2     26052   1.441871    0.805124
3     75136  13.147394    0.428964
4     38344   1.669788    0.134296
..      ...        ...         ...
995   11145   3.410627    0.631838
996   68846   9.974715    0.669787
997   26575  10.650102    0.866627
998   48111   9.134528    0.728045
999   43757   7.882601    1.332446

[1000 rows x 3 columns]

处理后的数据内容为：
[[ 0.33193158  0.41660188  0.24523407]
 [-0.87247784  0.13992897  1.69385734]
 [-0.34554872 -1.20667094 -0.05422437]
 ...
 [-0.32171752  0.96431572  0.06952649]
 [ 0.65959911  0.60699509 -0.20931587]
 [ 0.46120328  0.31183342  1.00680598]]

标准化后数据的均值为：-2.4276876805136757e-17
标准差为：1.0


# 4 特征降维

## 4.1 特征选择

### 4.1.1 Filter过滤式：主要探究特征本身特点、特征与特征和目标值之间关联

#### 4.1.1.1 方差选择法：低方差特征过滤 VarianceThreshold方法

In [12]:
# 先导包
import pandas as pd

# 导入特征选择模块中的 低方差特征删除工具
from sklearn.feature_selection import VarianceThreshold

# 实例化类对象，并设置阈值为37
vt = VarianceThreshold(threshold=37)

# 读取数据
f = pd.read_csv("factor_returns.csv")
data = f.iloc[: , 1: 10]

# 使用fit_transform方法对数据进行 低方差过滤
data_new = vt.fit_transform(data)

# 对比
print(f"原数据内容为：\n{data.shape}\n\n处理后的数据内容为：\n{data_new.shape}")

原数据内容为：
(2318, 9)

处理后的数据内容为：
(2318, 6)


#### 4.1.1.2 相关系数：特征与特征之间的相关程度

In [13]:
# 先导包
from scipy.stats import pearsonr

# 示例数据
x = [1, 2, 3, 4, 5]
y = [2, 4, 6, 8, 10]

# 计算相关系数和 p 值
correlation_coefficient, p_value = pearsonr(x, y)

# 输出结果
print(f"x和y的皮尔逊相关系数为：{correlation_coefficient}，p值为：{p_value}")

x和y的皮尔逊相关系数为：1.0，p值为：0.0


### 4.1.2 Embedded嵌入式：算法自动选择特征、特征与目标值之间的关联

#### 4.1.2.1 决策树

#### 4.1.2.2 正则化

#### 4.1.2.3 深度学习

## 4.2 主成分分析（PCA：Principal Component Analysis）

In [14]:
# 导入主成分分析类
from sklearn.decomposition import PCA

# 类对象实例化，这里希望保留原本的90%
pca = PCA(n_components=0.9)

# 准备数据
X = np.array([[2.5, 2.4], [0.5, 0.7], [2.2, 2.9], [1.9, 2.2], [3.1, 3.0], [2.3, 2.7], [2, 1.6], [1, 1.1], [1.5, 1.6], [1.1, 0.9]])

# 进行主成分分析
X_new = pca.fit_transform(X)
X_new

array([[-0.82797019],
       [ 1.77758033],
       [-0.99219749],
       [-0.27421042],
       [-1.67580142],
       [-0.9129491 ],
       [ 0.09910944],
       [ 1.14457216],
       [ 0.43804614],
       [ 1.22382056]])

# 三 分类算法

# 1 K-近邻算法（KNN算法：K-Nearest Neighbors）

根据输入数据点的 K 个最近邻居的类别或数值来进行预测。

K值取得过小，容易受到异常值的影响；K值取得过大，若样本不均衡，也容易出现偏差。故而需要合理调整k值的取值。

In [15]:
# 1. 先导包
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

# 2. 获取鸢尾花数据
iris = load_iris()

# 3. 划分数据集
x_train, x_test, y_train, y_test = train_test_split(iris.data, iris.target, random_state=37)

# 4. 特征工程：标准化
transfer = StandardScaler()
x_train = transfer.fit_transform(x_train)  # 训练集使用 fit_transform
x_test = transfer.transform(x_test)        # 测试集使用 transform

# 5. 估计器实例化，并对训练集进行拟合
estimator = KNeighborsClassifier(n_neighbors=3, algorithm="auto")
estimator.fit(x_train, y_train)

# 6. 模型评估
# 方法一：直接比对真实值和预测值
y_predict = estimator.predict(x_test)
print(f"使用方法一直接进行比对：\n{y_test == y_predict}\n")
# 方法二：计算准确率
score = estimator.score(x_test, y_test)
print(f"使用方法二计算准确率，得出准确率为：{score}")

使用方法一直接进行比对：
[ True  True  True  True  True  True  True  True  True False  True False
  True  True  True  True  True  True  True  True  True  True  True False
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True]

使用方法二计算准确率，得出准确率为：0.9210526315789473


# 2 模型选择与调优：sklearn.model_selection.GridSearchCV类

In [16]:
# 1. 先导包
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV

# 2. 获取鸢尾花数据
iris = load_iris()

# 3. 划分数据集
x_train, x_test, y_train, y_test = train_test_split(iris.data, iris.target, random_state=37)

# 4. 特征工程：标准化
transfer = StandardScaler()
x_train = transfer.fit_transform(x_train)  # 训练集使用 fit_transform
x_test = transfer.transform(x_test)        # 测试集使用 transform

# 5. 估计器实例化，加入网格搜索与交叉验证，并对训练集进行拟合
estimator = KNeighborsClassifier(algorithm="auto")

param_dict = {"n_neighbors": [1, 3, 5, 7, 9, 11]}
estimator = GridSearchCV(estimator, param_grid=param_dict, cv=10) # 这里将estimator修改了，添加了网格搜索与交叉验证

estimator.fit(x_train, y_train)

# 6. 模型评估
# 方法一：直接比对真实值和预测值
y_predict = estimator.predict(x_test)
print(f"使用方法一直接进行比对：\n{y_test == y_predict}\n")
# 方法二：计算准确率
score = estimator.score(x_test, y_test)
print(f"使用方法二计算准确率，得出准确率为：{score}\n")

# 7. 结果分析
print("最佳参数为：", estimator.best_params_)
print("最佳结果为：", estimator.best_score_)
print("最佳估计器为：", estimator.best_estimator_)
print(f"交叉验证结果:{estimator.cv_results_}")

使用方法一直接进行比对：
[ True  True  True  True  True  True  True  True  True False  True False
  True  True  True  True  True  True  True  True  True  True  True False
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True]

使用方法二计算准确率，得出准确率为：0.9210526315789473

最佳参数为： {'n_neighbors': 3}
最佳结果为： 0.9545454545454547
最佳估计器为： KNeighborsClassifier(n_neighbors=3)
交叉验证结果:{'mean_fit_time': array([0.00079575, 0.00075214, 0.00075209, 0.00081449, 0.00084438,
       0.00110664]), 'std_fit_time': array([0.00055698, 0.00051421, 0.0004039 , 0.00057545, 0.00044901,
       0.00059437]), 'mean_score_time': array([0.0019006 , 0.00185361, 0.00210435, 0.00194094, 0.00180502,
       0.0016464 ]), 'std_score_time': array([0.00057013, 0.00045066, 0.0005887 , 0.00056984, 0.00071882,
       0.00054068]), 'param_n_neighbors': masked_array(data=[1, 3, 5, 7, 9, 11],
             mask=[False, False, False, False, False, False],
       fill_value='?',
            dtype=object), 'params': [{'n_ne

# 3 朴素贝叶斯算法（Naive Bayes）

假设事件相互独立，则称为朴素贝叶斯。

## 3.1 多项式朴素贝叶斯

In [17]:
# 先导包
from sklearn.datasets import fetch_20newsgroups
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB

# 准备数据
news = fetch_20newsgroups(subset="all")  # all代表训练集和测试集都有。此参数的默认为train，意味着只有训练集。

# 划分数据集
x_train, x_test, y_train, y_test = train_test_split(news.data, news.target, random_state=37)

# 文本特征抽取
transfer = TfidfVectorizer()
x_train = transfer.fit_transform(x_train)
x_test = transfer.transform(x_test)

# 朴素贝叶斯算法
estimator = MultinomialNB()
estimator.fit(x_train, y_train)

# 模型评估
# 方法一：直接比对真实值和预测值
y_predict = estimator.predict(x_test)
print(f"使用方法一直接进行比对：\n{y_test == y_predict}\n")
# 方法二：计算准确率
score = estimator.score(x_test, y_test)
print(f"使用方法二计算准确率，得出准确率为：{score}\n")

使用方法一直接进行比对：
[ True  True  True ...  True  True  True]

使用方法二计算准确率，得出准确率为：0.847623089983022



# 4 决策树（Decision Tree）

高效地进行决策，按特征的先后顺序进行（越重要的越靠前）

## 4.1 创建决策树

In [18]:
# 先导包
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier

# 准备数据
iris = load_iris()

# 划分数据集
x_train, x_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.25, random_state=37)

# 决策树预估器
estimator = DecisionTreeClassifier()
estimator.fit(x_train, y_train)

# 模型评估
# 方法一：直接比对真实值和预测值
y_predict = estimator.predict(x_test)
print(f"使用方法一直接进行比对：\n{y_test == y_predict}\n")
# 方法二：计算准确率
score = estimator.score(x_test, y_test)
print(f"使用方法二计算准确率，得出准确率为：{score}\n")

使用方法一直接进行比对：
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True False
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True]

使用方法二计算准确率，得出准确率为：0.9736842105263158



## 4.2 使用决策树处理泰坦尼克号案例

In [19]:
# 先导包
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction import DictVectorizer

# 获取数据
data = pd.read_csv("titanic.csv")

# 筛选特征值和目标值
x = data[["pclass", "age", "sex"]]
y = data["survived"]

# 缺失值处理（因为age里面有缺失值，故而需要继续数据处理），并转换为字典格式
x.loc[:, "age"] = x["age"].fillna(x["age"].mean())
x = x.to_dict(orient="records")

# 划分数据集
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=37)

# 字典特征抽取
transfer = DictVectorizer()
x_train = transfer.fit_transform(x_train)
x_test = transfer.transform(x_test)

# 决策树预估器
estimator = DecisionTreeClassifier(criterion="entropy")
estimator.fit(x_train, y_train)

# 模型评估
# 方法一：直接比对真实值和预测值
y_predict = estimator.predict(x_test)
print(f"使用方法一直接进行比对：\n{y_test == y_predict}\n")
# 方法二：计算准确率
score = estimator.score(x_test, y_test)
print(f"使用方法二计算准确率，得出准确率为：{score}\n")

使用方法一直接进行比对：
645     True
308     True
558     True
983     True
647     True
        ... 
498     True
422     True
1160    True
967     True
103     True
Name: survived, Length: 329, dtype: bool

使用方法二计算准确率，得出准确率为：0.8024316109422492



C:\Users\Lenovo\AppData\Local\Temp\ipykernel_57156\1144736630.py:15: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x.loc[:, "age"] = x["age"].fillna(x["age"].mean())


# 5 随机森林

定义：随机森林是一种用于分类和回归任务的集成学习方法。它通过构建多个决策树，并将它们的输出合并，以提高准确性并控制过拟合。

## 5.1 使用随机森林对4.2的泰坦尼克号进行预测

In [20]:
# 先导包
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction import DictVectorizer

# 获取数据
data = pd.read_csv("titanic.csv")

# 筛选特征值和目标值
x = data[["pclass", "age", "sex"]]
y = data["survived"]

# 缺失值处理（因为age里面有缺失值，故而需要继续数据处理），并转换为字典格式
x.loc[:, "age"] = x["age"].fillna(x["age"].mean())
x = x.to_dict(orient="records")

# 划分数据集
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=37)

# 字典特征抽取
transfer = DictVectorizer()
x_train = transfer.fit_transform(x_train)
x_test = transfer.transform(x_test)

# 随机森林预估器
estimator = RandomForestClassifier(criterion="entropy")
estimator.fit(x_train, y_train)

# 模型评估
# 方法一：直接比对真实值和预测值
y_predict = estimator.predict(x_test)
print(f"使用方法一直接进行比对：\n{y_test == y_predict}\n")
# 方法二：计算准确率
score = estimator.score(x_test, y_test)
print(f"使用方法二计算准确率，得出准确率为：{score}\n")

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_57156\4248802369.py:15: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x.loc[:, "age"] = x["age"].fillna(x["age"].mean())


使用方法一直接进行比对：
645     True
308     True
558     True
983     True
647     True
        ... 
498     True
422     True
1160    True
967     True
103     True
Name: survived, Length: 329, dtype: bool

使用方法二计算准确率，得出准确率为：0.7993920972644377



## 5.2 使用调优后的随机森林对4.2的泰坦尼克号进行预测

In [21]:
# 先导包
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction import DictVectorizer
from sklearn.model_selection import GridSearchCV

# 获取数据
data = pd.read_csv("titanic.csv")

# 筛选特征值和目标值
x = data[["pclass", "age", "sex"]]
y = data["survived"]

# 缺失值处理（因为age里面有缺失值，故而需要继续数据处理），并转换为字典格式
x.loc[:, "age"] = x["age"].fillna(x["age"].mean())
x = x.to_dict(orient="records")

# 划分数据集
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=37)

# 字典特征抽取
transfer = DictVectorizer()
x_train = transfer.fit_transform(x_train)
x_test = transfer.transform(x_test)

# 随机森林预估器
estimator = RandomForestClassifier(criterion="entropy")

# 加入网格搜索与交叉验证
# 参数准备
param_dict = {"n_estimators" : [1, 3, 5, 7, 9, 11], "max_depth" : [5, 8, 15, 25, 30]}
estimator = GridSearchCV(estimator, param_grid=param_dict, cv=3)
estimator.fit(x_train, y_train)

# 模型评估
# 方法一：直接比对真实值和预测值
y_predict = estimator.predict(x_test)
print(f"使用方法一直接进行比对：\n{y_test == y_predict}\n")
# 方法二：计算准确率
score = estimator.score(x_test, y_test)
print(f"使用方法二计算准确率，得出准确率为：{score}\n")

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_57156\1179159403.py:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x.loc[:, "age"] = x["age"].fillna(x["age"].mean())


使用方法一直接进行比对：
645      True
308      True
558      True
983      True
647     False
        ...  
498      True
422      True
1160     True
967      True
103      True
Name: survived, Length: 329, dtype: bool

使用方法二计算准确率，得出准确率为：0.8389057750759878



# 四 回归与聚类（无监督，即无目标）算法

# 1 线性回归（优化算法）

说明：下面的误差大，原因是因为红酒数据集中没有线性关系，因为波士顿房价已经被移除了

## 1.1 正规方程：sklearn.linear_model.LinearRegression（一次到位）

In [22]:
# 先导包
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression

# 准备数据
california= fetch_california_housing()

# 划分数据集
x_train, x_test, y_train,y_test = train_test_split(california.data, california.target, random_state=37)

# 特征预处理：标准化
transfer = StandardScaler()
x_train = transfer.fit_transform(x_train)
x_test = transfer.transform(x_test)

# 正规方程估计器
estimator = LinearRegression()
estimator.fit(x_train, y_train)

# 得出模型
print(f"正规方程的权重系数为：\n{estimator.coef_}")
print(f"正规方程的偏置（截距）为：\n{estimator.intercept_}")

正规方程的权重系数为：
[ 0.82307315  0.12362376 -0.25208115  0.29331978  0.00288605 -0.04115082
 -0.9030782  -0.87714227]
正规方程的偏置（截距）为：
2.070364167958359


## 1.2 梯度下降：sklearn.linear_model.SGDRegressor（多次拟合）

In [23]:
# 先导包
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import SGDRegressor

# 准备数据
california= fetch_california_housing()

# 划分数据集
x_train, x_test, y_train,y_test = train_test_split(california.data, california.target, random_state=37)

# 特征预处理：标准化
transfer = StandardScaler()
x_train = transfer.fit_transform(x_train)
x_test = transfer.transform(x_test)

# 梯度下降估计器
estimator = SGDRegressor()
estimator.fit(x_train, y_train)

# 得出模型
print(f"梯度下降的权重系数为：\n{estimator.coef_}")
print(f"梯度下降的偏置（截距）为：\n{estimator.intercept_}")

梯度下降的权重系数为：
[ 0.80852936  0.12979843 -0.18931008  0.26667587  0.01630997 -0.04075928
 -0.90610236 -0.90317095]
梯度下降的偏置（截距）为：
[2.06456281]


## 1.3 回归性能评估

### 1.3.1 均方误差（Mean Squared Error, MSE）

均方误差主要用于衡量预测值与真实值之间的差距，它是回归问题中最常见的损失函数之一。

下求 ： 上述正规方程和梯度下降的均方误差

In [24]:
# 先导包
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# 准备数据
california= fetch_california_housing()

# 划分数据集
x_train, x_test, y_train,y_test = train_test_split(california.data, california.target, random_state=37)

# 特征预处理：标准化
transfer = StandardScaler()
x_train = transfer.fit_transform(x_train)
x_test = transfer.transform(x_test)

# 正规方程估计器
estimator = LinearRegression()
estimator.fit(x_train, y_train)

# 得出模型
print(f"正规方程的权重系数为：\n{estimator.coef_}")
print(f"正规方程的偏置（截距）为：\n{estimator.intercept_}")

# 均方误差评估
y_predict = estimator.predict(x_test)
print(f"\n预测房价为：\n{y_predict}")
error = mean_squared_error(y_test, y_predict, squared=True)
print(f"均方误差为：\n{error}")

正规方程的权重系数为：
[ 0.82307315  0.12362376 -0.25208115  0.29331978  0.00288605 -0.04115082
 -0.9030782  -0.87714227]
正规方程的偏置（截距）为：
2.070364167958359

预测房价为：
[1.32323615 1.64298298 0.50423978 ... 2.7116062  2.44334217 1.45822224]
均方误差为：
0.5096750578766663


In [25]:
# 先导包
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import SGDRegressor
from sklearn.metrics import mean_squared_error

# 准备数据
california= fetch_california_housing()

# 划分数据集
x_train, x_test, y_train,y_test = train_test_split(california.data, california.target, random_state=37)

# 特征预处理：标准化
transfer = StandardScaler()
x_train = transfer.fit_transform(x_train)
x_test = transfer.transform(x_test)

# 梯度下降估计器
estimator = SGDRegressor()
estimator.fit(x_train, y_train)

# 得出模型
print(f"梯度下降的权重系数为：\n{estimator.coef_}")
print(f"梯度下降的偏置（截距）为：\n{estimator.intercept_}")

# 均方误差评估
y_predict = estimator.predict(x_test)
print(f"\n预测房价为：\n{y_predict}")
error = mean_squared_error(y_test, y_predict, squared=True)
print(f"均方误差为：\n{error}")

梯度下降的权重系数为：
[ 0.80385689  0.14155439 -0.23518863  0.29028435  0.01983835 -0.03270678
 -0.89186901 -0.8675867 ]
梯度下降的偏置（截距）为：
[2.06039786]

预测房价为：
[1.34128328 1.65326828 0.49952932 ... 2.67501059 2.46601871 1.47420974]
均方误差为：
0.5115981182579206


# 2 欠拟合和过拟合

欠拟合：由于模型过于简单，无法捕捉数据中的重要模式，导致模型在训练集和测试集上的性能都很差。特征为模型的训练误差和测试误差都很高。

过拟合：由于模型过于复杂，捕捉了数据中的噪声而非真实模式，导致模型在训练集上表现良好，但在测试集上表现不佳。

## 2.1 正则化（应对过拟合）

## 2.2 岭回归（带有L2正则化的线性回归）

In [26]:
# 先导包
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error

# 获取数据
california = fetch_california_housing()

# 划分数据集
x_train, x_test, y_train, y_test = train_test_split(california.data, california.target, random_state=37)

# 数据标准化
transfer = StandardScaler()
x_train = transfer.fit_transform(x_train)
x_test = transfer.transform(x_test)

# 预估器
estimator = Ridge()
estimator.fit(x_train, y_train)

# 得出模型
print(f"岭回归的权重系数为：\n{estimator.coef_}")
print(f"岭回归的偏置（截距）为：\n{estimator.intercept_}")

# 均方误差评估
y_predict = estimator.predict(x_test)
print(f"\n预测房价为：\n{y_predict}")
error = mean_squared_error(y_test, y_predict, squared=True)
print(f"岭回归的均方误差为：\n{error}")

岭回归的权重系数为：
[ 0.82304135  0.12371089 -0.25191297  0.29309756  0.00291594 -0.04115598
 -0.90224737 -0.87630386]
岭回归的偏置（截距）为：
2.070364167958359

预测房价为：
[1.32318056 1.64341054 0.50469793 ... 2.71140393 2.44326814 1.45817639]
岭回归的均方误差为：
0.5096820050449234


# 3 逻辑回归

与线性回归之间有联系，但是逻辑回归属于分类算法！

常用于解决二分类问题，即：是/否

## 3.1 逻辑回归对癌症分类

In [27]:
# 先导包
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

# 1、读取数据
path = "https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/breast-cancer-wisconsin.data"
column_name = ['Sample code number', 'Clump Thickness', 'Uniformity of Cell Size', 'Uniformity of Cell Shape',
                   'Marginal Adhesion', 'Single Epithelial Cell Size', 'Bare Nuclei', 'Bland Chromatin',
                   'Normal Nucleoli', 'Mitoses', 'Class']
data = pd.read_csv(path, names=column_name)

# 2、缺失值处理
# 1）替换  -->  np.nan
data = data.replace(to_replace="?", value=np.nan)
# 2）删除缺失样本
data.dropna(inplace=True)

# 3、筛选特征值和目标值
x = data.iloc[:, 1:-1]
y = data["Class"]

# 4、划分数据集
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=37, test_size=0.2)

# 5、预估器流程
estimator = LogisticRegression()  # 实例化
estimator.fit(x_train, y_train)

# 6、逻辑回归的模型参数：回归系数和偏置
coef = estimator.coef_   # 模型系数
intercept = estimator.intercept_  # 截距
print(f"估计器的模型系数为：\n{coef}")
print(f"估计器的截距为：{intercept}")

# 7、模型评估
# 方法1：直接比对真实值和预测值
y_predict = estimator.predict(x_test)
print("y_predict:\n", y_predict)
print("直接比对真实值和预测值:\n", y_test == y_predict)

# 方法2：计算准确率
score = estimator.score(x_test, y_test)
print("准确率为：\n", score)

估计器的模型系数为：
[[ 0.51033318 -0.05682976  0.41828484  0.35540447  0.06736245  0.2895899
   0.50260394  0.24346757  0.2497843 ]]
估计器的截距为：[-9.75960563]
y_predict:
 [4 4 4 2 2 4 4 4 2 2 2 4 2 2 4 4 4 2 2 2 2 2 2 2 4 2 4 2 4 2 4 2 4 4 4 2 4
 2 2 2 4 2 4 4 2 2 2 4 4 4 2 2 2 4 4 2 2 2 4 2 2 2 2 2 2 2 4 2 4 4 2 4 4 2
 2 4 4 2 2 2 4 4 2 4 2 2 4 4 2 4 4 2 2 4 2 2 4 2 2 2 4 2 2 2 4 2 4 2 2 2 2
 2 2 2 2 2 2 2 4 4 2 2 2 2 2 2 4 2 4 2 2 4 2 4 4 2 4]
直接比对真实值和预测值:
 132    True
98     True
152    True
507    True
504    True
       ... 
490    True
55     True
436    True
133    True
636    True
Name: Class, Length: 137, dtype: bool
准确率为：
 0.9635036496350365


# 4 分类的评估方法

## 4.1 样本均衡的情况

### 4.1.1 分类评估报告：sklearn.metrics.classification_report方法

精确率（Precision）：预测结果为正例样本中真实为正例的比例。

召回率（Recall）：真实为正例的样本中预测结果为正例的比例。（即正例被标记为正例的比例）

F1评分： 公式： 2 (Precision × Recall) / (Precision + Recall)， 反映模型的稳健性

上述三个模型主要用于二分类问题，但是多分类问题也可以使用

In [28]:
# 先导包
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

# 1、读取数据
path = "https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/breast-cancer-wisconsin.data"
column_name = ['Sample code number', 'Clump Thickness', 'Uniformity of Cell Size', 'Uniformity of Cell Shape',
                   'Marginal Adhesion', 'Single Epithelial Cell Size', 'Bare Nuclei', 'Bland Chromatin',
                   'Normal Nucleoli', 'Mitoses', 'Class']
data = pd.read_csv(path, names=column_name)

# 2、缺失值处理
# 1）替换  -->  np.nan
data = data.replace(to_replace="?", value=np.nan)
# 2）删除缺失样本
data.dropna(inplace=True)

# 3、筛选特征值和目标值
x = data.iloc[:, 1:-1]
y = data["Class"]

# 4、划分数据集
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=37, test_size=0.2)

# 5、预估器流程
estimator = LogisticRegression()  # 实例化
estimator.fit(x_train, y_train)

# 6、逻辑回归的模型参数：回归系数和偏置
coef = estimator.coef_   # 模型系数
intercept = estimator.intercept_  # 截距
print(f"估计器的模型系数为：\n{coef}")
print(f"估计器的截距为：{intercept}")

# 7、模型评估
# 方法1：直接比对真实值和预测值
y_predict = estimator.predict(x_test)
print("y_predict:\n", y_predict)
print("直接比对真实值和预测值:\n", y_test == y_predict)

# 方法2：计算准确率
score = estimator.score(x_test, y_test)
print("准确率为：\n", score)

# 8、使用分类评估方法
# 先导包
from sklearn.metrics import classification_report
report = classification_report(y_test, y_predict, labels=[2, 4], target_names=["良性", "恶性"])
print("\n", report)

估计器的模型系数为：
[[ 0.51033318 -0.05682976  0.41828484  0.35540447  0.06736245  0.2895899
   0.50260394  0.24346757  0.2497843 ]]
估计器的截距为：[-9.75960563]
y_predict:
 [4 4 4 2 2 4 4 4 2 2 2 4 2 2 4 4 4 2 2 2 2 2 2 2 4 2 4 2 4 2 4 2 4 4 4 2 4
 2 2 2 4 2 4 4 2 2 2 4 4 4 2 2 2 4 4 2 2 2 4 2 2 2 2 2 2 2 4 2 4 4 2 4 4 2
 2 4 4 2 2 2 4 4 2 4 2 2 4 4 2 4 4 2 2 4 2 2 4 2 2 2 4 2 2 2 4 2 4 2 2 2 2
 2 2 2 2 2 2 2 4 4 2 2 2 2 2 2 4 2 4 2 2 4 2 4 4 2 4]
直接比对真实值和预测值:
 132    True
98     True
152    True
507    True
504    True
       ... 
490    True
55     True
436    True
133    True
636    True
Name: Class, Length: 137, dtype: bool
准确率为：
 0.9635036496350365

               precision    recall  f1-score   support

          良性       0.96      0.98      0.97        82
          恶性       0.96      0.95      0.95        55

    accuracy                           0.96       137
   macro avg       0.96      0.96      0.96       137
weighted avg       0.96      0.96      0.96       137



### 4.1.2 只获得精确率、召回率、F1分数

In [29]:
# 先导包
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

# 1、读取数据
path = "https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/breast-cancer-wisconsin.data"
column_name = ['Sample code number', 'Clump Thickness', 'Uniformity of Cell Size', 'Uniformity of Cell Shape',
                   'Marginal Adhesion', 'Single Epithelial Cell Size', 'Bare Nuclei', 'Bland Chromatin',
                   'Normal Nucleoli', 'Mitoses', 'Class']
data = pd.read_csv(path, names=column_name)

# 2、缺失值处理
# 1）替换  -->  np.nan
data = data.replace(to_replace="?", value=np.nan)
# 2）删除缺失样本
data.dropna(inplace=True)

# 3、筛选特征值和目标值
x = data.iloc[:, 1:-1]
y = data["Class"]

# 4、划分数据集
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=37, test_size=0.2)

# 5、预估器流程
estimator = LogisticRegression()  # 实例化
estimator.fit(x_train, y_train)

# 6、逻辑回归的模型参数：回归系数和偏置
coef = estimator.coef_   # 模型系数
intercept = estimator.intercept_  # 截距
print(f"估计器的模型系数为：\n{coef}")
print(f"估计器的截距为：{intercept}")

# 7、模型评估
# 方法1：直接比对真实值和预测值
y_predict = estimator.predict(x_test)
print("y_predict:\n", y_predict)
print("直接比对真实值和预测值:\n", y_test == y_predict)

# 方法2：计算准确率
score = estimator.score(x_test, y_test)
print("准确率为：\n", score)

# 8、直接使用单一方法获取
from sklearn.metrics import accuracy_score
precision = accuracy_score(y_test, y_predict)
print(f'\n逻辑回归的准确率为: {precision}\n')

from sklearn.metrics import recall_score
recall = recall_score(y_test, y_predict, average='macro')
print(f'逻辑回归的召回率为: {recall}\n')

from sklearn.metrics import f1_score
f1 = f1_score(y_test, y_predict, average='macro')
print(f'逻辑回归的F1分数为: {f1}')

估计器的模型系数为：
[[ 0.51033318 -0.05682976  0.41828484  0.35540447  0.06736245  0.2895899
   0.50260394  0.24346757  0.2497843 ]]
估计器的截距为：[-9.75960563]
y_predict:
 [4 4 4 2 2 4 4 4 2 2 2 4 2 2 4 4 4 2 2 2 2 2 2 2 4 2 4 2 4 2 4 2 4 4 4 2 4
 2 2 2 4 2 4 4 2 2 2 4 4 4 2 2 2 4 4 2 2 2 4 2 2 2 2 2 2 2 4 2 4 4 2 4 4 2
 2 4 4 2 2 2 4 4 2 4 2 2 4 4 2 4 4 2 2 4 2 2 4 2 2 2 4 2 2 2 4 2 4 2 2 2 2
 2 2 2 2 2 2 2 4 4 2 2 2 2 2 2 4 2 4 2 2 4 2 4 4 2 4]
直接比对真实值和预测值:
 132    True
98     True
152    True
507    True
504    True
       ... 
490    True
55     True
436    True
133    True
636    True
Name: Class, Length: 137, dtype: bool
准确率为：
 0.9635036496350365

逻辑回归的准确率为: 0.9635036496350365

逻辑回归的召回率为: 0.9605321507760531

逻辑回归的F1分数为: 0.9619127050319711


## 4.2 样本不均衡的情况

### 4.2.1 ROC曲线、AUC值

TPR = TP / (TP + FN) ：所有真实类别为1的样本中，预测类别为1的比例。

FPR = FP / (FP + TN) ：所有真实类别为0的样本中，预测类别为1的比例。

ROC曲线的横轴就是FPRate，纵轴就是TPRate，当两者相等时，意味着AUC值为0.5。

AUC值 即 ROC曲线的面积

AUC的最高值为1，最低值为0.5，越接近于1越好。

AUC只能用于二分类问题，且非常适用于评价样本不均衡中的分类器性能

In [30]:
# 先导包
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

# 1、读取数据
path = "https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/breast-cancer-wisconsin.data"
column_name = ['Sample code number', 'Clump Thickness', 'Uniformity of Cell Size', 'Uniformity of Cell Shape',
                   'Marginal Adhesion', 'Single Epithelial Cell Size', 'Bare Nuclei', 'Bland Chromatin',
                   'Normal Nucleoli', 'Mitoses', 'Class']
data = pd.read_csv(path, names=column_name)

# 2、缺失值处理
# 1）替换  -->  np.nan
data = data.replace(to_replace="?", value=np.nan)
# 2）删除缺失样本
data.dropna(inplace=True)

# 3、筛选特征值和目标值
x = data.iloc[:, 1:-1]
y = data["Class"]

# 4、划分数据集
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=37, test_size=0.2)

# 5、预估器流程
estimator = LogisticRegression()  # 实例化
estimator.fit(x_train, y_train)

# 6、展示AUC值的使用方法
from sklearn.metrics import roc_auc_score
# 使用np.where将y_test转换为要求的格式
y_true = np.where(y_test > 3, 1, 0)
# 准备预测数据
y_predict = estimator.predict(x_test)
# 使用roc_auc_score方法
auc_value = roc_auc_score(y_true, y_predict)
print(f"所得AUC值为：{auc_value}")

所得AUC值为：0.960532150776053


# 5 模型的保存和加载（joblib库）

## 5.1 模型的保存和加载API

### 5.1.1 模型保存

In [31]:
# 先导包
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge

# 获取数据
california = fetch_california_housing()

# 划分数据集
x_train, x_test, y_train, y_test = train_test_split(california.data, california.target, random_state=37)

# 数据标准化
transfer = StandardScaler()
x_train = transfer.fit_transform(x_train)
x_test = transfer.transform(x_test)

# 预估器
estimator = Ridge()
estimator.fit(x_train, y_train)

# 保存模型
import joblib
joblib.dump(estimator, "岭回归.pkl")

['岭回归.pkl']

### 5.1.2 模型加载（这里不需要导入岭回归类）

In [32]:
# 先导包
import joblib

# 加载模型
estimator = joblib.load("岭回归.pkl")

# 加载数据，注意对于这个数据集，之前的岭回归均方误差为0.5096820050449234
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error

# 获取数据
california = fetch_california_housing()

# 划分数据集
x_train, x_test, y_train, y_test = train_test_split(california.data, california.target, random_state=37)

# 数据标准化
transfer = StandardScaler()
x_train = transfer.fit_transform(x_train)
x_test = transfer.transform(x_test)

# 均方误差评估
y_predict = estimator.predict(x_test)
print(f"\n预测房价为：\n{y_predict}")
error = mean_squared_error(y_test, y_predict, squared=True)
print(f"岭回归的均方误差为：\n{error}")


预测房价为：
[1.32318056 1.64341054 0.50469793 ... 2.71140393 2.44326814 1.45817639]
岭回归的均方误差为：
0.5096820050449234


# 6 无监督算法 K-means算法